spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    hostName: 127.0.0.1
    port: 6379
    password: geovis
#    timeout: 5000
    #最大空闲数
    maxIdle: 20
    #连接池的最大数据库连接数
    maxActive: -1
    #控制一个pool可分配多少个jedis实例,用来替换上面的maxActive
    maxTotal: 100
    #最大建立连接等待时间。如果超过此时间将接到异常
    maxWaitMillis: 100
    #连接的最小空闲时间
    minEvictableIdleTimeMillis: 864000000
    #每次释放连接的最大数目
    numTestsPerEvictionRun: 10
    #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程
    timeBetweenEvictionRunsMillis: 300000
    #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
    testOnBorrow: true
    #在空闲时检查有效性
    testWhileIdle: false
    #数据库
    database: 0

  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true

  application:
    name: springboot

  rabbitmq:
    host: 127.0.0.1
    port: 15672
    username: admin
    password: admin
  servlet:
    multipart:
      max-request-size: 10024MB
      max-file-size: 10024MB
server:
  port: 9000
  servlet:
    context-path: /springboot

mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  file: ../logs/${spring.application.name}.log
  level:
    com.lhst.springboot_project.controller: debug





person:
  lastName: zhangsan
  age: 20
  boss: false
  birth: 2020/9/17
  maps: {"1",111,"2",222}
  lists:
    -wang
    -zhang
    -li
  dog:
    name: dog
    age: 1